const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = vm.createContext({console,document:{addEventListener(){},querySelector(){return null}},window:{addEventListener(){}}});
const source = fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8').replace(/writeAppHistory\("home", true\);\s*restoreSession\(\);\s*$/, '');
vm.runInContext(source,context);
const run = code => vm.runInContext(code,context);
assert.ok(run(`optionsMarkup().includes('data-mode="lote">MOVIMENTOS')`));
assert.ok(!run(`optionsMarkup().includes('MODO LOTE') || optionsMarkup().includes('data-mode="movimentos"')`));
assert.ok(run(`optionsMarkup().includes('public/options/lote.svg')`));
run(`const originalRender=render;render=()=>{};persistBatchDraft=()=>{};showMovementNotice=()=>{};
 state.mode='lote';state.batch={...emptyBatchState(),movementType:'saida',phase:'scan'};
 findSet=code=>({code:code==='11111111'?'100':'200',ean:code,name:'Test'});
 let release;let stockReads=0;
 getLocationStock=async()=>{stockReads++;if(stockReads===1)await new Promise(resolve=>release=resolve);return [{storage:'A',stock:5}];};`);
(async()=>{
 run(`state.query='11111111';const first=addCodeToBatch(state.query);`);
 await Promise.resolve();
 assert.equal(run(`state.query`),'');
 run(`state.query='22222222';const second=addCodeToBatch(state.query);state.query='333';`);
 run(`release()`);
 await run(`Promise.all([first,second])`);
 assert.equal(run(`state.batch.items.length`),2);
 assert.equal(run(`state.query`),'333');
 assert.equal(run(`batchUnitCount()`),2);
 await run(`addCodeToBatch('11111111')`);
 assert.equal(run(`state.batch.items.length`),2);
 assert.equal(run(`batchItemByCode('100').qty`),2);
 assert.equal(run(`batchUnitCount()`),3);
 run(`state.scannerOpen=true;state.mode='lote';batchMarkup=()=>'<p>Updated count</p>';headerMarkup=()=>'';
 updateLotMobileHeaderSummary=()=>{};renderBatchKeypadWindow=()=>{};
 const liveVideo={srcObject:'live-stream'};const content={innerHTML:''};
 const app={innerHTML:'original scanner',querySelector:selector=>selector==='.camera-scanner'?liveVideo:selector==='.app-content'?content:null,insertAdjacentHTML(){}};
 document.querySelector=selector=>selector==='#app'?app:null;originalRender();`);
 assert.equal(run(`app.innerHTML`),'original scanner');
 assert.equal(run(`liveVideo.srcObject`),'live-stream');
 assert.equal(run(`content.innerHTML`),'<p>Updated count</p>');
 console.log('Batch reading tests passed: merged home action, consecutive EANs, pending stock validation, repeat quantities and live camera preservation.');
})().catch(error=>{console.error(error);process.exitCode=1;});
