const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = vm.createContext({console,document:{addEventListener(){}},window:{addEventListener(){}}});
const source = fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8').replace(/writeAppHistory\("home", true\);\s*restoreSession\(\);\s*$/, '');
vm.runInContext(source,context);
const run = code => vm.runInContext(code,context);
run(`function movement(qty,cost,origin='',code='100'){const row=[];row[0]=code;row[5]=origin;row[8]=qty;row[13]=cost;return row;}`);
assert.equal(run(`inventoryCosts([movement(2,10),movement(3,15),movement(-4,0),movement(1,20)]).get('100').cost`),16.5);
assert.equal(run(`inventoryCosts([movement(2,10),movement(-2,''),movement(3,20)]).get('100').cost`),20);
assert.equal(run(`inventoryCosts([movement(2,''),movement(3,20)]).get('100').cost`),null);
assert.equal(run(`inventoryCosts([movement(2,0),movement(2,10)]).get('100').cost`),5);
assert.equal(run(`inventoryCosts([movement(2,10),movement(-1,10,'Transferência'),movement(1,10,'Transferência')]).get('100').cost`),10);
assert.equal(run(`inventoryCosts([movement(1,12,'','CUSTOM-12345670')]).get('CUSTOM-12345670').cost`),12);
for(const value of ['',null,undefined,-1,'abc',' '])assert.throws(()=>run(`entryCost(${JSON.stringify(value)})`),/ENTRY_COST_REQUIRED/);
assert.equal(run(`entryCost('12,50')`),12.5);
assert.equal(run(`entryCost('0')`),0);
run(`state.mode='entrada';state.selected={code:'100',name:'Test'};state.movementForm=emptyMovementForm();`);
assert.ok(run(`foundMarkup().includes('data-movement-field="cost"')`));
run(`state.mode='saida'`);
assert.ok(!run(`foundMarkup().includes('data-movement-field="cost"')`));
console.log('Cost tests passed');
